version: "3"

services:

  pokt-graphql:
    image: pokt-graphql
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      - DEBUG=1
      - POCKET_RPC_URL=http://host.docker.internal:8081/v1
